# Generated by Django 3.2.4 on 2021-07-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='roommaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.TextField(max_length=5)),
                ('capacity', models.IntegerField()),
                ('status', models.IntegerField()),
                ('room_cat', models.TextField(max_length=50)),
            ],
        ),
    ]
