# Generated by Django 3.2.4 on 2021-07-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_roommaster_room_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('datentime', models.TextField()),
                ('Name', models.TextField(max_length=50)),
                ('room_alloted', models.TextField(max_length=5)),
                ('rent', models.IntegerField()),
                ('advance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('adatentime', models.TextField()),
                ('ddatentime', models.TextField()),
                ('Name', models.TextField(max_length=50)),
                ('room_no', models.TextField(max_length=5)),
                ('rent', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('payable_amt', models.IntegerField()),
            ],
        ),
    ]
